spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

stripe:
  api:
    secret: ${STRIPE_API_SECRET_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET_KEY}

client:
  url: ${CLIENT_URL}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

jwt:
  secretKey: ${JWT_SECRET_KEY}